---
name: Dispatch a SSH session

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'ngok token'
        required: true
        default: ''

jobs:
  start_ssh_session:
    runs-on: ubuntu-20.04
    name: Start the SSH session
    steps:
    - name: Start SSH session
      uses: luchihoratiu/debug-via-ssh@main
      with:
        NGROK_AUTH_TOKEN: ${{ github.event.inputs.token }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
