---
name: Dispatch a SSH session

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'ngok token'
        required: true
        default: ''

jobs:
  start_ssh_session:
    runs-on: ubuntu-20.04
    name: Start the SSH session
    steps:
    - name: Start SSH session
      #uses: luchihoratiu/debug-via-ssh@main
      #with:
      #  NGROK_AUTH_TOKEN: ${{ github.event.inputs.token }}
      #  SSH_PASS: ${{ secrets.SSH_PASS }}
      run: |
        printf "# Preparing environment..."
          whoami > ssh_user
        printf " [DONE]\n\n"
        
        echo "# Change the SSH user password"
        echo "${{ secrets.SSH_PASS }}`n${{ secrets.SSH_PASS }}" | sudo passwd $(cat ssh_user)
        shell: pwsh

    - name: Start Cloudflared
      run: |
        echo "# Install Cloudflared"
          curl --location --silent  https://github.com/cloudflare/cloudflared/releases/download/2024.6.1/cloudflared-linux-amd64 --output cloudflared
          chmod +x ./cloudflared
        echo "# Starting Cloudflared..."
          nohup ./cloudflared tunnel --no-autoupdate --protocol http2 --url tcp://localhost:22 2>&1 | tee cloudflared.log | sed -u 's/^/cloudflared: /' &
          cloudflared_pid=$!
        printf " [DONE]\n\n"
        
        url=$(head -1 <(tail -f cloudflared.log | grep --line-buffered -o 'https://.*\.trycloudflare.com'))
        echo "#########################################"
        echo $url
        echo "#########################################"
        tmux wait-for channel
        echo 'Session ended'

        kill "$cloudflared_pid"
        shell: bash
